[package]

name = "rustation"
# Exported as VERSION and VERSION_CSTR in the library
version = "0.0.1"
authors = ["Lionel Flandrin <lionel.flandrin@gmail.com>"]

description = "A PlayStation emulator"
homepage = "https://github.com/simias/rustation"
repository = "https://github.com/simias/rustation"
documentation = "https://github.com/simias/rustation/wiki"
readme = "README.md"
license = "GPL-2.0+"
keywords = ["emulator", "playstation"]

[dependencies]

#glium = "0.10.0"

[lib]
name = "rustation"
crate-type = ["rlib"]
